services:
  db:
    image: ghcr.io/arinji2/blue-bucks-db
    container_name: pocketbase-db      
    ports:
      - "58:8090"                    
    volumes:
      - ./db/pb_data:/pb/pb_data
      - ./db/pb_migrations:/pb/pb_migrations
      - ./db/pb_hooks:/pb/pb_hooks
  api:
    image: ghcr.io/arinji2/blue-bucks-api
    container_name: golang-api      
    volumes:
      - ./api/.env:/app/.env
    ports:
      - "59:8080"                    
